import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import {
  normalizeVariants,
  syncVariants,
  recomputeProductCache,
  buildDefaultVariant,
} from '@/lib/variants'

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url)
    const category = searchParams.get('category')
    const search = searchParams.get('search')
    const featured = searchParams.get('featured')
    const newArrival = searchParams.get('newArrival')
    const bestSeller = searchParams.get('bestSeller')
    const sort = searchParams.get('sort') || 'newest'
    const minPrice = searchParams.get('minPrice')
    const maxPrice = searchParams.get('maxPrice')

    const where: any = {}
    if (category && category !== 'all') where.categorySlug = category
    if (featured === 'true') where.featured = true
    if (newArrival === 'true') where.newArrival = true
    if (bestSeller === 'true') where.bestSeller = true
    if (search) {
      where.OR = [
        { name: { contains: search } },
        { description: { contains: search } },
      ]
    }
    if (minPrice || maxPrice) {
      where.price = {}
      if (minPrice) where.price.gte = parseFloat(minPrice)
      if (maxPrice) where.price.lte = parseFloat(maxPrice)
    }

    let orderBy: any = { createdAt: 'desc' }
    if (sort === 'price_asc') orderBy = { price: 'asc' }
    if (sort === 'price_desc') orderBy = { price: 'desc' }

    const products = await db.product.findMany({
      where,
      orderBy,
      include: {
        variants: {
          orderBy: { order: 'asc' },
        },
      },
    })
    return NextResponse.json({ success: true, products })
  } catch (error: any) {
    console.error('[Products GET] Error:', error?.message || error)
    return NextResponse.json({ success: false, error: 'Failed to fetch products' }, { status: 500 })
  }
}

export async function POST(req: NextRequest) {
  try {
    const data = await req.json()
    const rawVariants = data.variants
    delete data.variants

    // ── Ensure slug is unique ──
    if (data.slug) {
      let slug = data.slug as string
      let attempts = 0
      while (attempts < 5) {
        const existing = await db.product.findUnique({ where: { slug } })
        if (!existing) break
        attempts++
        slug = `${data.slug}-${Date.now()}`
      }
      data.slug = slug
    }

    // ── Sanitize & default fields ──
    if (typeof data.price === 'string') data.price = parseFloat(data.price) || 0
    if (typeof data.comparePrice === 'string') data.comparePrice = parseFloat(data.comparePrice) || null
    if (data.comparePrice === '') data.comparePrice = null
    if (typeof data.stock === 'string') data.stock = parseInt(data.stock) || 0
    if (!data.images) data.images = '[]'
    if (!data.benefits) data.benefits = '[]'
    if (!data.ingredients) data.ingredients = ''
    if (!data.howToUse) data.howToUse = ''

    // Ensure boolean fields
    data.featured = data.featured === true
    data.newArrival = data.newArrival === true
    data.bestSeller = data.bestSeller === true
    data.freeShipping = data.freeShipping === true

    // Remove id if present (auto-generated by Prisma)
    delete data.id

    // Create product first (with denormalized price/stock as a placeholder),
    // then sync variants which recomputes the cache.
    const product = await db.$transaction(async (tx) => {
      const created = await tx.product.create({ data })

      const variantInputs = normalizeVariants(rawVariants)
      const finalVariants =
        variantInputs.length > 0
          ? variantInputs
          : [buildDefaultVariant(created.price, created.stock, created.comparePrice)]

      await syncVariants(tx, created.id, finalVariants)
      await recomputeProductCache(tx, created.id)

      return tx.product.findUnique({
        where: { id: created.id },
        include: { variants: { orderBy: { order: 'asc' } } },
      })
    })

    return NextResponse.json({ success: true, product })
  } catch (error: any) {
    console.error('[Products POST] Error:', error?.message || error)

    // Return specific error for duplicate slug
    if (error?.message?.includes('Unique constraint failed')) {
      return NextResponse.json(
        { success: false, error: 'A product with this name already exists. Please use a different name.' },
        { status: 409 },
      )
    }

    return NextResponse.json(
      { success: false, error: error?.message || 'Failed to create product' },
      { status: 500 },
    )
  }
}
